version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/job"
    schedule:
      interval: "monthly"
    groups:
      patch:
        update-types:
          - "patch"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
    groups:
      all-providers:
        patterns:
          - "*"
