version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: pip
    directory: /job
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: monthly
