tfc_organization_name = "Doarakko"
tfc_workspace_name    = "kagoole-twitter"
gcp_project_id        = "kagoole-379522"
gcp_region            = "asia-northeast1"
gh_repo_name          = "Doarakko/kagoole-twitter"
