name: deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'job/**'
      - 'terraform/**'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/631578640507/locations/global/workloadIdentityPools/gh-oidc-pool/providers/gh-oidc-provider'
          service_account: 'github-actions@kagoole-379522.iam.gserviceaccount.com'
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:job"
          push: true
          tags: asia-northeast1-docker.pkg.dev/kagoole-379522/kagoole/twitter:latest
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2.0.1'
      - name: deploy job
        run: |
          gcloud components install beta
          gcloud beta run jobs deploy kagoole-twitter --image asia-northeast1-docker.pkg.dev/kagoole-379522/kagoole/twitter --region asia-northeast1
